# Generated by Django 2.1.7 on 2019-03-29 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
